# Generated by Django 4.2.2 on 2023-07-14 18:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_rename_alumnos_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='Observaciones',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
