# Generated by Django 4.2.2 on 2023-07-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_alumno_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='Observaciones',
        ),
        migrations.AddField(
            model_name='alumno',
            name='comentarios',
            field=models.TextField(null=True),
        ),
    ]
