# Generated by Django 4.2.2 on 2023-07-14 19:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_remove_alumno_observaciones_alumno_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='comentarios',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
