# Generated by Django 4.2.2 on 2023-07-14 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_alter_alumno_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='f_alta',
            field=models.DateField(default=datetime.date(2023, 7, 14)),
        ),
    ]
